language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install coveralls
    - pip install coverage
script: 
    - nosetests --with-coverage --cover-package wrapple -v

after_success: coveralls
