language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install coveralls
    - pip install coverage
script: 
    - nosetests --with-coverage --cover-package wrapple -v

after_success: coveralls

notifications:
  webhooks: http://104.131.120.228:8080/hubot/travisci/general
  on_start: true
